### ISSUE TITLE
usesearchterms or searchterms

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#12]
I noticed that the usage of `?mode=searchterms` in https://idr-testing.openmicroscopy.org/searchengineapi/api/v1/resources/all/keys/?mode=searchterms
is not documented at http://idr-testing.openmicroscopy.org/searchengineapi/apidocs/#/Available%20keys%20(attributes)%20for%20a%20resource/get_searchengineapi_api_v1_resources__resource_table__keys_

I was looking for it because I noticed that the `mode` here ("searchterms") is different from the`"mode": "usesearchterms"` used in the `searchannotation` query. But, in the current UI these get mixed-up, so that after unchecking `Show all attributes` and updating the form, the query shown in the right textarea now has `"mode": "searchterms"`.

Probably best to use `searchterms` everywhere (instead of `usesearchterms`)?

cc @khaledk2

**Comment by will-moore** [comment]
How is the `mode` used when submitting a query? Does it make any difference if you use an invalid value?

**Comment by khaledk2** [comment]
mode is used only with the kyes endpoint and is not used with the submitquery, I have removed it from the query example in apidcos.
