### ISSUE TITLE
OR search has fewer results than AND

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#32]
Using [/searchengine/api/v1/resources/submitquery/](
https://idr-testing.openmicroscopy.org/searchengine/apidocs/#/Mixed%20Complex%20query/post_searchengine__api_v1_resources_submitquery_) 

This query gives 187 images:
```
{
 "query_details": {
 "and_filters": [],
 "or_filters": [
   [{"name": "Gene Symbol", "value": "pax7", "operator": "equals", "resource": "image"},
    {"name": "Antibody", "value": "seh1-fl antibody", "operator": "equals", "resource": "image"}]
  ],
  "case_sensitive": false
  }
}
```
but if I search for only 1 of the `or_filters` above I get more, e.g. this gives 1880 images:
```
{
    "query_details": {
      "and_filters": [{"name": "Gene Symbol", "value": "pax7", "operator": "equals", "resource": "image"}],
      "or_filters": [],
       "case_sensitive": false
     }
}
```

**Comment by pwalczysko** [comment]
Another example 

```
{
 "query_details": {
 "and_filters": [],
 "or_filters": [
   [{"name": "Antibody", "value": "pax7", "operator": "equals", "resource": "image"}]
  ],
  "case_sensitive": false
  }
}
``` 

delivers 143 results.

But

```
{
 "query_details": {
 "and_filters": [],
 "or_filters": [
   [{"name": "Organism Part", "value": "pax6", "operator": "equals", "resource": "image"},
    {"name": "Antibody", "value": "pax7", "operator": "equals", "resource": "image"}]
  ],
  "case_sensitive": false
  }
}
```

delivers no results (the second "or" filter delivers really no results, but in the OR situation, the total number of results should be still 143.

**Comment by pwalczysko** [comment]
Actually, reading the two examples (the @will-moore's from the description, and mine from https://github.com/ome/omero_search_engine/issues/32#issuecomment-1220947339), they are quite different (but both are reporting a bug). @will-moore is adding the single query into the "and" filters, whereas in https://github.com/ome/omero_search_engine/issues/32#issuecomment-1220947339 I am leaving the single query in the "or" filters. Both cases together probably point to the

 "combined OR search does not work correctly, no matter how you check the single query"

**Comment by khaledk2** [comment]
I have checked the code and the examples which you have provided. I have found a bug which affects `or` conditions in some cases. I have fixed it and will push it.
