### ISSUE TITLE
submitquery resource project or screen

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#36]
I accidentally entered this query in `/submitquery/` search:

```
{
    "query_details": {
      "and_filters": [
        {"name": "Name (IDR number)", "value": "idr0002-heriche-condensation/screenA", "operator": "equals", "resource": "project"}
      ],
      "or_filters": [],
       "case_sensitive": false
     }
}
```

The Name matches a `Screen` but I also had `"resource": "project"` so I guess I expected to get no results, but I got `1152` results, same as with "screen" (so maybe these are interchangeable?)

I did get no results using `study (error), plate (error), image (empty list)`

**Comment by khaledk2** [comment]
This has been fixed in PR #69.
