### ISSUE TITLE
Change to common searchterms

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#45]
In discussion with @pwalczysko @jburel @francesw today, we decided on some changes to the common search terms:

To be removed from the list at https://idr-testing.openmicroscopy.org/searchengine/api/v1/resources/all/keys/?mode=searchterms

 - Gene Name
 - Organism
 - Organism Part

To be added:

 - Gene Identifier

Also, the Organism key-value pair on Images should be ignored by the search engine (since this is duplicated on the Project/Screen). The current behaviour of existing IDR search is to use the key/value on the Project/Screen to search by Organism, so we would like to stick with this behaviour for search engine, at least initially.
So, e.g. this endpoint shouldn't return `Organism: mus muscularis`:  
https://idr-testing.openmicroscopy.org/searchengine/api/v1/resources/image/searchvalues/?value=mus

**Comment by sbesson** [comment]
> Also, the Organism key-value pair on Images should be ignored by the search engine (since this is duplicated on the Project/Screen).

With the notable exception of the multi-organism screens or experiments (`idr0053` or `idr0134` are the two examples coming to mind immediately) where the annotation at the Project/Screen level is not sufficient to filter images and the Organism annotation at the Image level allows to discriminate between organisms.
Not claiming this should be considered for the first phase as the assumption above will apply to 98% of IDR data but that's something we might need to revisit eventually

**Comment by jburel** [comment]
I think we agree that it will need to be reviewed after phase I. Currently it brings too much confusion

**Comment by khaledk2** [comment]
This has been implemented on PR #49
