### ISSUE TITLE
ignore wildcard searches

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#50]
Searching for `*` or `?` should query for strings containing those literal characters, and they shouldn't be treated as wild-cards.

cc @pwalczysko

**Comment by khaledk2** [comment]
Currently, search for any value supports using `*` and  `?` and can be used if agreed upon, the following are some examples to explain it:

- `protein with*`: will search for all values starting with `protein with` and any thing after it
- `*protein with`: will return all the values ending with `protein with`
- `*protein with*`: will return all the values which contain the `protein with`, regardless of position (this is the default now as the two `*` are added by the search engine before searching the values).
- `g*fp`: will return all the values starting with `g` and ending with `fb`.
- `gfpt?`: will return all the values which have 5 characters, starting with `gfpt`, and the last character can be anything.
- `?gfpt`: will return all the values which have 5 characters, ending with `gfpt`, and the first character can be anything.

**Comment by pwalczysko** [comment]
> Currently, search for any value supports using `*` and `?`, the following are some examples to explain it:
> 
>     * `protein with*`: will search for all values starting with `protein with` and any thing after it
> 
>     * `*protein with`: will return all the values ending with `protein with`
> 
>     * `*protein with*`: will return all the values which contain the `protein with`, regardless of position (this is the default now as the two `*` are added by the search engine before searching the values).
> 
>     * `g*fp`: will return all the values starting with `g` and ending with `fb`.
> 
>     * `gfpt?`: will return all the values which have 5 characters, starting with `gfpt`, and the last character can be anything.
> 
>     * `?gfpt`: will return all the values which have 5 characters, ending with `gfpt`, and the first character can be anything.

thanks @khaledk2 for the explanation. The spirit of the issue here is that we want to remove such behaviour as explained by yourself. As discussed at the meeting. Is it possible to remove this behaviour described by yourself in favor of the behaviour

> Searching for * or ? should query for strings containing those literal characters, and they shouldn't be treated as wild-cards.

please ?

**Comment by khaledk2** [comment]
THis has been implemented on PR #51
