### ISSUE TITLE
"Name (IDR number)" shouldn't be part of the search-engine API

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#55]
The term `Name (IDR number)` is just an IDR-specific UI prompt for users.
But it shouldn't be part of an "OMERO"-based API.
E.g. it is returned from:
https://idr-testing.openmicroscopy.org/searchengine/api/v1/resources/all/keys/?mode=searchterms

I'm not sure if it is still used elsewhere, but it should be replaced with `Name` everywhere.

**Comment by will-moore** [comment]
@khaledk2 Now that I am working with searching for containers by Name, this issue has come up again.
I don't really want to use the term `Name (IDR number)` in searches since it feels like it should be changed and I don't want to hard-code this key in the UI.

Also, it's used in URL parameters and is harder to use. E.g. this is not such a nice URL:
/search/?key=Name+%28IDR+number%29&value=idr0123&operator=contains&resource=project

compared with:
/search/?key=Name&value=idr0123&operator=contains&resource=project

**Comment by will-moore** [comment]
We also need to update the response from https://idr-testing.openmicroscopy.org/searchengine/api/v1/resources/all/keys/?mode=searchterms
which includes `"Name (IDR number)"`

**Comment by khaledk2** [comment]
It returns `name` now instead of `Name (IDR number)`
