### ISSUE TITLE
Bug: submitquery/containers/ not finding projects

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#67]
/searchengine//api/v1/resources/submitquery/containers/
With this query finds nothing:
```
{
  "query_details": {
    "and_filters": [
      {
        "name": "Name (IDR number)",
        "value": "idr0123-mota-mifish/experimentA",
        "operator": "equals",
        "resource": "project"
      }
    ],
    "or_filters": [],
    "case_sensitive": false
  }
}

``` 
returns:
```
{
  "Error": "Your query returns no results"
}
```

But if I change the "value" to "idr0008-rohn-actinome/screenB" then it does find results.
"idr0120-german-immunologicalsynapse/screenA" works OK, 
but "idr0120-german-immunologicalsynapse" returns empty results:
```
"results": {
    "results": []
  },
```

**Comment by khaledk2** [comment]
It was a bug in PR #57 and has been fixed. I deployed the fix in `idr-testing`, please check and let me know if you still have this issue.

**Comment by will-moore** [comment]
This is fixed, thanks.
