### ISSUE TITLE
too many images returned from /submitquery

### ISSUE THREAD

**Issue by will-moore** [ome/omero_search_engine#75]
At `/searchengine//api/v1/resources/submitquery/` this query should only return a single Image (since there is only 1 image in the `idr0068-shah-zebrafishlightsheet/experimentA` study.
But it returns many images.

```
{
  "query_details": {
    "and_filters": [
      {
        "name": "Imaging Method",
        "value": "light",
        "operator": "contains",
        "resource": "container"
      },
      {
        "name": "name",
        "value": "idr0068-shah-zebrafishlightsheet/experimentA",
        "operator": "equals",
        "resource": "container"
      }
    ],
    "or_filters": [],
    "case_sensitive": false
  }
}
```

**Comment by khaledk2** [comment]
@will-moore It has been fixed and deployed in `idr-testing`, please check it and let me know if you still have this issue.

**Comment by will-moore** [comment]
Looks fixed. Thanks!
