### ISSUE TITLE
Building immutable Docker images

### ISSUE THREAD

**Issue by sbesson** [ome/omero_search_engine#9]
See https://github.com/IDR/deployment/pull/369#issuecomment-1115964445

The current GitHub workflow builds a `latest` Docker image on every push for this repository which allows to easily update an IDR deployment with the latest changes. However, the usage of a single mutable Docker image tag is problematic for deploying this application in a production state as it prevents deterministic deployments. This will become increasingly apparent as the search engine starts being deployed on multiple deployments.

The most authoritative solution would be to start relying on image hashes. This has the downside of making the relationship between the deployed Docker image and the version of the upstream code more opaque.

Another solution used in the OME repository is to use a sysem of tags with a set of conventions. For instanve, looking at https://hub.docker.com/r/openmicroscopy/omero-server/tags

- the `x.y.z-b` Docker tag is expected to be immutable by convention and will match the equivalent Git tag pushed to the source code repository on GitHub
- the `x.y.z`, `x.y`, `x` and `latest` Docker tags are mutable and will be updated on every tag push
- if a rebuild of the image is required, a new tag `x.y.z-(b+1)` will be pushed

@khaledk2 what are your thoughts about adopting a similar strategy here so that e.g. we could start relying on `openmicroscopy/omero-searchengine:x.y.z`?

**Comment by khaledk2** [comment]
I think we have implemented that
